name: bego
description: "Business Ocean (Bego) - Flutter Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  becomponent:
    path: ../../packages/component
  becore:
    path: ../../packages/core
  beui:
    path: ../../packages/ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.3
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
