name: uibook
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  becomponent:
    path: ../../packages/component
  beui:
    path: ../../packages/ui
  becore:
    path: ../../packages/core
  flutter:
    sdk: flutter
  path: ^1.9.1
  widgetbook: ^3.11.0
  widgetbook_annotation: ^3.3.0

dev_dependencies:
  build_runner: ^2.4.15

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.10.0

flutter:
  uses-material-design: true
